sudo: false
dist: xenial
language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p "$HOME/miniconda"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --add channels conda-forge
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env
install:
  - conda install python=$TRAVIS_PYTHON_VERSION setuptools root scipy matplotlib uncertainties xorg-libx11 cmake pytest pytest-cov codecov compilers
  - conda install -c op3 libmfile
  - python setup.py install
script:
  - pytest --cov-report term
after_success:
  - codecov
#  - test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-client && bash conda/conda_upload.sh
