matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
      language: generic
      env:
        - PY_VER=3.6
        - OS=linux-64
    - os: linux
      dist: bionic
      sudo: false
      language: generic
      env:
        - PY_VER=3.7
        - OS=linux-64

env:
  global:
    - PKG_NAME=hdtv
    - CONDA_BLD_PATH=${HOME}/conda-bld

stages:
  - name: deploy
    if: branch = master
    if: tag IS present

#cache:
#  directories:
#    - ${HOME}/miniconda

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p "$HOME/miniconda"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda info -a
  - sed -i -E 's/^(python)/\1='$PY_VER'/' ./environment.yml
  - conda env create -n hdtv
  - source activate hdtv
  - conda list
install:
  - python setup.py install
script:
  - pytest --cov-report term
after_success:
  - codecov
#deploy:
#  - conda install conda-build anaconda-client
#  - conda build .
#  - anaconda -t $CONDA_UPLOAD_TOKEN upload -u $CONDA_USER $CONDA_BLD_PATH/$OS/$PKG_NAME-`date +%Y.%m.%d`-0.tar.bz2
