matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
      language: generic
      env:
        - PY_VER=3.6
        - OS=linux-64
    - os: linux
      dist: bionic
      sudo: false
      language: generic
      env:
        - PY_VER=3.7
        - OS=linux-64

env:
  global:
    - PKG_NAME=hdtv
    - CONDA_BLD_PATH=${HOME}/conda-bld

stages:
  - name: deploy
    if: branch = master
    if: tag IS present

#cache:
#  directories:
#    - ${HOME}/miniconda

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p "$HOME/miniconda"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --add channels conda-forge
  - conda config --add channels op3
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
install:
  - conda install python=$PY_VER setuptools root scipy matplotlib uncertainties xorg-libx11 cmake pytest pytest-cov codecov compilers libmfile
  - python setup.py install
script:
  - export CPATH="$HOME/miniconda/envs/base/lib:$CPATH"
  - export LD_LIBRARY_PATH="$HOME/miniconda/envs/base/lib:$LD_LIBRARY_PATH"
  - export LIBRARY_PATH="$HOME/miniconda/envs/base/lib:$LIBRARY_PATH"
  - pytest --cov-report term
after_success:
  - codecov
#deploy:
#  - conda install conda-build anaconda-client
#  - conda build .
#  - anaconda -t $CONDA_UPLOAD_TOKEN upload -u $CONDA_USER $CONDA_BLD_PATH/$OS/$PKG_NAME-`date +%Y.%m.%d`-0.tar.bz2
