name: hdtv
channels:
  - conda-forge
  - op3
  - defaults
dependencies:
  - python
  - setuptools
  - root
  - scipy
  - matplotlib
  - uncertainties
  - xorg-libx11
  - cmake
  - pytest
  - pytest-cov
  - codecov
  - compilers
  - libmfile
  - ipython
  - prompt_toolkit=2.0.10
  - traits
  - make
